[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["pip install -r apps/api/requirements.txt"]

[start]
cmd = "cd apps/api && uvicorn src.app.main:app --host 0.0.0.0 --port $PORT"
