services:
  postgres:
    image: postgres:16
    container_name: sqlpet_postgres
    environment:
      POSTGRES_DB=petdb
      POSTGRES_USER=pet
      POSTGRES_PASSWORD=pet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: